#!/bin/bash
FILE=""
HOST=""
PORT=1313
OPERATION=""


YELLOW='\033[0;33m'
GREEN='\033[1;32m'
RED='\033[1;31m'
NC='\033[0m'


while getopts "h:f:p:RTv" opt; do
  case $opt in
    h) HOST="$OPTARG"
    ;;
    f) FILE="$OPTARG"
    ;;
    p) PORT="$OPTARG"
    ;;
    R) OPERATION="R"
    ;;
    T) OPERATION="T"
    ;;
    v) echo "Transfer v.1.0 by PrankyMat Feb-20-2015"; exit 0
    ;;
    \?) echo "Invalid option -$OPTARG" >&2
    ;;
  esac
done


function logError {
  MESSAGE=""
  case $1 in
    PORT) MESSAGE="Port not specified! \n\t  * Please specify port with -p port"
    ;;
    OPERATION) MESSAGE="Operation not specified! \n\t  * Please use -R for receive -T for transmit"
    ;;
    FILE) MESSAGE="File argument not specified!\n\t * Please specify file with -f filename"
    ;;
    HOST) MESSAGE="Host not specified!\n\t * Please specify host with -h hostname"
    ;;
    *) MESSAGE=$1
    ;;
  esac

  echo -e "[${RED}Error${NC}] $MESSAGE ${NC}"
}

function logSuccess {
  MESSAGE=""
  case $1 in
    PORT) MESSAGE="Port not specified! \n\t  * Please specify port with -p port"
    ;;
    *) MESSAGE=$1
    ;;
  esac

  echo -e "[${GREEN}Success${NC}] $MESSAGE ${NC}"
}


if [[ $OPERATION == "" ]]; then
  logError "OPERATION"
  exit 1
fi

if [[ $FILE == "" ]]; then
  logError "FILE"
  exit 1
fi

if [[ $OPERATION == "R" ]]; then
  if [[ $PORT == "" ]]; then
    logError "PORT"
    exit 1
  fi

  echo -e "Waiting file at port: ${RED}$PORT${NC} and output to file: '${YELLOW}$FILE${NC}'..."
  nc -l "$PORT" > "$FILE"
  exit 0
elif [[ $OPERATION == "T" ]]; then
  if [[ $HOST == "" ]]; then
    logError "HOST"
    exit 1
  fi
  if [[ $PORT == "" ]]; then
    logError "PORT"
    exit 1
  fi

  echo "Sending '$FILE' to $HOST:$PORT"
  nc "$HOST" "$PORT" < "$FILE"
  logSuccess "Done transmitting file: '${YELLOW}$FILE${NC}'"
  exit 0
fi
